messages:
  ridecount_update: "<gold>Your ridecount for <ride> is now <ridecount></reset>"

database:
  # Database type support
  # File
  # - sqlite
  # Remote Database
  # - mariadb
  type: sqlite

  # When using SQLite (Default)
  # Data file name (plugins/TC-Ridecounters/{path})
  path: "ridecounters_data.db"

  # When using MariaDB
  username: "username"
  password: "password"
  connectionTimeout: 10000
  # jdbc:mariadb://[host]:[port]/[database name]
  connectionUrl: "jdbc:mariadb://127.0.0.1:3306/ridecounters"

check_for_updates: true